CREATE TABLE [dbo].[SS_SQLMAPSTORE](
	[SQLID] [nvarchar](100) NOT NULL,
	[SQLTEXT] [ntext] NOT NULL,
	[CUID] [nvarchar](20) NOT NULL,
	[CDATE] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_SS_SQLMAPSTORE] PRIMARY KEY CLUSTERED 
(
	[SQLID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


CREATE TABLE [dbo].[SS_SQLMAPSTORE_AUTH](
	[USER_ID] [nvarchar](20) NOT NULL,
	[USER_NAME] [nvarchar](200) NOT NULL,
	[USER_PHONE] [nvarchar](20) NOT NULL,
	[USER_PWD] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_SS_SQLMAPSTORE_AUTH] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[SS_SQLMAPSTORE_LOG](
	[SQLID] [nvarchar](100) NOT NULL,
	[SQC] [int] NOT NULL,
	[CDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[USER_ID] [nvarchar](20) NOT NULL,
	[LOG_TYPE] [nchar](1) NOT NULL DEFAULT (N'C'),
	[LOG_DESC] [nvarchar](200) NOT NULL,
	[LOG_BEFORE] [ntext] NOT NULL,
	[LOG_AFTER] [ntext] NOT NULL,
 CONSTRAINT [PK_SS_SQLMAPSTORE_LOG] PRIMARY KEY CLUSTERED 
(
	[SQLID] ASC,
	[SQC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



CREATE TABLE [dbo].[SS_SQLMAPSTORE_USAGE](
	[SQLID] [nvarchar](100) NOT NULL,
	[PGM_ID] [nvarchar](200) NOT NULL,
	[CDATE] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_SS_SQLMAPSTORE_USAGE] PRIMARY KEY CLUSTERED 
(
	[SQLID] ASC,
	[PGM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



---------------------

