
CREATE TABLE MOBISUSER.SS_MSG_ID
(
  MSG_ID          CHAR(6 BYTE),
  APP_TYPE        CHAR(1 BYTE)                  DEFAULT ' ' CONSTRAINT SS_MSG_ID_NN1 NOT NULL,
  MSG_DIRECT      VARCHAR2(2000 BYTE) CONSTRAINT SS_MSG_ID_NN5 NOT NULL,
  MSG_TYPE        CHAR(2 BYTE)                  DEFAULT ' ' CONSTRAINT SS_MSG_ID_NN6 NOT NULL,
  MSG_TEXT_KO_KR  VARCHAR2(200 BYTE) CONSTRAINT SS_MSG_ID_NN7 NOT NULL,
  MSG_TEXT_EN_US  VARCHAR2(200 BYTE) CONSTRAINT SS_MSG_ID_NN8 NOT NULL,
  MSG_TEXT_LO_LN  VARCHAR2(200 BYTE) CONSTRAINT SS_MSG_ID_NN9 NOT NULL,
  REG_DATE        CHAR(8 BYTE)                    DEFAULT ' ' CONSTRAINT SS_DICTIONARY_NN1 NOT NULL,
  REG_TIME        CHAR(6 BYTE)                    DEFAULT ' ' CONSTRAINT SS_DICTIONARY_NN2 NOT NULL,
  USER_ID        CHAR(10 BYTE)                   DEFAULT ' ' CONSTRAINT SS_DICTIONARY_NN3 NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    5
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MOBISUSER.SS_MSG_ID IS '??? ID ??';

 

CREATE UNIQUE INDEX MOBISUSER.SS_MSG_ID_PK ON MOBISUSER.SS_MSG_ID
(MSG_ID)
NOLOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MOBISUSER.SS_MSG_ID ADD (
  CONSTRAINT SS_MSG_ID_PK
  PRIMARY KEY
  (MSG_ID)
  USING INDEX MOBISUSER.SS_MSG_ID_PK
  ENABLE VALIDATE);






CREATE TABLE MOBISUSER.SS_DICTIONARY
(
  DIC_ID        VARCHAR2(100 BYTE),
  DIC_NM_EN_US  VARCHAR2(100 BYTE),
  DIC_NM_KO_KR  VARCHAR2(100 BYTE),
  DIC_NM_LO_LN  VARCHAR2(100 BYTE),
  REG_DATE        CHAR(8 BYTE)                    DEFAULT ' ' CONSTRAINT SS_DICTIONARY_NN1 NOT NULL,
  REG_TIME        CHAR(6 BYTE)                    DEFAULT ' ' CONSTRAINT SS_DICTIONARY_NN2 NOT NULL,
  USER_ID        CHAR(10 BYTE)                   DEFAULT ' ' CONSTRAINT SS_DICTIONARY_NN3 NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    5
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          512K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MOBISUSER.SS_DICTIONARY IS '????';

 

CREATE INDEX MOBISUSER.SS_DICTIONARY_I1 ON MOBISUSER.SS_DICTIONARY
(TRIM("DIC_ID"))
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MOBISUSER.SS_DICTIONARY_PK ON MOBISUSER.SS_DICTIONARY
(DIC_ID)
NOLOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MOBISUSER.SS_DICTIONARY ADD (
  CONSTRAINT SS_DICTIONARY_PK
  PRIMARY KEY
  (DIC_ID)
  USING INDEX MOBISUSER.SS_DICTIONARY_PK
  ENABLE VALIDATE);

