
  CREATE TABLE "MOBISUSER"."MP_USER_SCREEN" 
   ("SYSTEM_CODE" CHAR(2 BYTE), 
	"USER_GROUP_CODE" CHAR(2 BYTE), 
	"SCREEN_ID" CHAR(10 BYTE), 
	"SCREEN_AUTHORITY" CHAR(1 BYTE) DEFAULT ' ' CONSTRAINT "MP_USER_SCREEN_NN1" NOT NULL ENABLE, 
	"REG_DATE" CHAR(8 BYTE) DEFAULT ' ' CONSTRAINT "MP_USER_SCREEN_NN2" NOT NULL ENABLE, 
	"REG_TIME" CHAR(6 BYTE) DEFAULT ' ' CONSTRAINT "MP_USER_SCREEN_NN3" NOT NULL ENABLE, 
	"USER_ID" CHAR(10 BYTE) DEFAULT ' ' CONSTRAINT "MP_USER_SCREEN_NN4" NOT NULL ENABLE, 
	 CONSTRAINT "MP_USER_SCREEN_PK" PRIMARY KEY ("SYSTEM_CODE", "USER_GROUP_CODE", "SCREEN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 5 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 393216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON TABLE "MOBISUSER"."MP_USER_SCREEN"  IS '??? ????';
 
  CREATE INDEX "MOBISUSER"."MP_USER_SCREEN_I1" ON "MOBISUSER"."MP_USER_SCREEN" ("USER_GROUP_CODE", "SCREEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
